<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="TeamCity.VSTest.TestAdapter" Version="1.0.41" />
        <PackageReference Include="FluentAssertions" Version="7.2.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nevermore.Analyzers\Nevermore.Analyzers.csproj" />
      <ProjectReference Include="..\Nevermore\Nevermore.csproj" />
    </ItemGroup>
</Project>
