version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ThisIsATest!
  test:
    build: .
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - NevermoreTestServer=db
      - NevermoreTestUsername=sa
      - NevermoreTestPassword=ThisIsATest!
  # mssqltools:
  #   image: mcr.microsoft.com/mssql-tools
  #   depends_on:
  #     - db
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t